AllCops:
  EnabledByDefault: true

Style/Copyright:
  Enabled: false
  AutocorrectNotice: 'Copyright (c) 2021 by Tehzwen'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120


Style/DocumentationMethod:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Style/ClassAndModuleChildren:
  Enabled: true